"""Newcastle Airport (NCL) destinations — May 2026."""

DESTINATIONS = {
    "NCL": {
        "name": "Newcastle",
        "routes": {
            "ACE": "Lanzarote",
            "ADB": "Izmir",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ARN": "Stockholm",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGO": "Bergen",
            "BJV": "Bodrum",
            "BOJ": "Bourgas",
            "BRS": "Bristol",
            "BRU": "Brussels",
            "BUD": "Budapest",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CGN": "Cologne",
            "CHQ": "Chania",
            "CMF": "Chambery",
            "CPH": "Copenhagen",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "DUS": "Dusseldorf",
            "EFL": "Kefalonia",
            "EXT": "Exeter",
            "FAO": "Faro",
            "FCO": "Rome",
            "FNC": "Funchal",
            "FRA": "Frankfurt",
            "FUE": "Fuerteventura",
            "GDN": "Gdansk",
            "GNB": "Grenoble",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HAM": "Hamburg",
            "HER": "Heraklion",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "IST": "Istanbul",
            "JER": "Jersey",
            "JSI": "Skiathos",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KRK": "Krakow",
            "LCA": "Larnaca",
            "LHR": "London Heathrow",
            "LIS": "Lisbon",
            "LPA": "Gran Canaria",
            "LYS": "Lyon",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MUC": "Munich",
            "MXP": "Milan",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NQY": "Newquay",
            "OPO": "Porto",
            "OSL": "Oslo",
            "PFO": "Paphos",
            "PMI": "Palma",
            "PMO": "Palermo",
            "PRG": "Prague",
            "PVK": "Preveza",
            "RAK": "Marrakech",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RVN": "Rovaniemi",
            "SKG": "Thessaloniki",
            "SOF": "Sofia",
            "SOU": "Southampton",
            "STR": "Stuttgart",
            "SVG": "Stavanger",
            "SZG": "Salzburg",
            "TFS": "Tenerife",
            "TRN": "Turin",
            "VCE": "Venice",
            "VIE": "Vienna",
            "VRN": "Verona",
            "WAW": "Warsaw",
            "WRO": "Wroclaw",
            "ZAD": "Zadar",
            "ZTH": "Zante",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
